In [ ]:
# Лабораторная работа №1
## Выполнил студент группы 1бПМ2 СтрекаловРВ
### Задание №1
# Поздороваться с миром

In [198]:
 print("Hello, World!")

Hello, World!


In [199]:
#Задание №2 
# Написать генератор случайных матриц

In [200]:
import numpy as np 
import random
import copy

m = input("Введите число строк: ")
n = input("Введите число столбцов: ")
min_lim = input("Введите min элементов: ")
max_lim = input("Введите max элементов: ")

def check(num):
    try:
        int(num)
        return True
    except ValueError:
        return False 

if (check(m) == False):
    m = 50;
if (check(n) == False):
    n = 50;
if (check(min_lim) == False):
    min_lim = -250;
if (check(max_lim) == False):
    max_lim = 1010;
    
m = int(m); n = int(n); min_lim = int(min_lim); max_lim = int(max_lim);
    
print (m,n,min_lim,max_lim)

def creatMarix():
    matrix = np.zeros([int(m),int(n)])
    for i in range(int(m)):
        for j in range(int(n)):
            matrix[i][j] = round(random.random() * (max_lim - min_lim) + min_lim)
    return matrix
    
MATRIX = creatMarix()
print (MATRIX)

matrix_2 = copy.deepcopy(MATRIX);
matrix0 = copy.deepcopy(MATRIX); 
matrix1 = copy.deepcopy(MATRIX);

Введите число строк: 10
Введите число столбцов: 10
Введите min элементов: 1
Введите max элементов: 10
10 10 1 10
[[ 3.  2.  3.  5.  6.  6.  4.  3.  7.  5.]
 [ 3.  8.  1. 10.  2.  2.  4.  3.  9.  9.]
 [10.  8.  7.  8.  9. 10.  6.  7.  2.  5.]
 [ 9.  8.  2.  9.  8.  9.  9.  3.  3.  5.]
 [ 4.  2.  3.  6.  6.  2.  7. 10.  8.  9.]
 [ 8.  7.  6.  3.  8.  9.  9.  6.  1. 10.]
 [10.  9.  4.  9.  6.  5.  4.  1.  6.  6.]
 [ 7.  8.  6.  3.  5.  9.  8.  9.  5. 10.]
 [10.  9.  5.  2. 10.  1.  6.  2.  2.  6.]
 [ 7.  2.  8.  9.  6.  6.  8.  6.  4.  3.]]


In [201]:
#Задание №3 
#Реализовать методы сортировки строк числовой матрицы в соответствии с заданием

In [202]:
import copy
import time

stime = time.time()

#сортировка выбором
def sorting_by_choice(array):
    for i in range(m):
        for j in range(n):
            p = j 
            k = j + 1
            while k < n:
                if array[i][k] < array[i][p]:
                    p = k
                k += 1
            array[i][j], array[i][p] = array[i][p], array[i][j]   
            
#Просто матрицы
print(MATRIX, "\n")
sort1 = copy.deepcopy(MATRIX);

#сортировка выбором
sorting_by_choice(sort1)
print(sort1, "\n")

print("Время выполнения : ", time.time() - stime)

[[ 3.  2.  3.  5.  6.  6.  4.  3.  7.  5.]
 [ 3.  8.  1. 10.  2.  2.  4.  3.  9.  9.]
 [10.  8.  7.  8.  9. 10.  6.  7.  2.  5.]
 [ 9.  8.  2.  9.  8.  9.  9.  3.  3.  5.]
 [ 4.  2.  3.  6.  6.  2.  7. 10.  8.  9.]
 [ 8.  7.  6.  3.  8.  9.  9.  6.  1. 10.]
 [10.  9.  4.  9.  6.  5.  4.  1.  6.  6.]
 [ 7.  8.  6.  3.  5.  9.  8.  9.  5. 10.]
 [10.  9.  5.  2. 10.  1.  6.  2.  2.  6.]
 [ 7.  2.  8.  9.  6.  6.  8.  6.  4.  3.]] 

[[ 2.  3.  3.  3.  4.  5.  5.  6.  6.  7.]
 [ 1.  2.  2.  3.  3.  4.  8.  9.  9. 10.]
 [ 2.  5.  6.  7.  7.  8.  8.  9. 10. 10.]
 [ 2.  3.  3.  5.  8.  8.  9.  9.  9.  9.]
 [ 2.  2.  3.  4.  6.  6.  7.  8.  9. 10.]
 [ 1.  3.  6.  6.  7.  8.  8.  9.  9. 10.]
 [ 1.  4.  4.  5.  6.  6.  6.  9.  9. 10.]
 [ 3.  5.  5.  6.  7.  8.  8.  9.  9. 10.]
 [ 1.  2.  2.  2.  5.  6.  6.  9. 10. 10.]
 [ 2.  3.  4.  6.  6.  6.  7.  8.  8.  9.]] 

Время выполнения :  0.0040018558502197266


In [203]:
#сортировка вставкой

stime = time.time()

def insert_sorting(data):
    for i in range(m):
        for j in range(n):
            k = j - 1 
            key = data[i][j]
            while data[i][k] > key and k >= 0:
                data[i][k + 1] = data[i][k]
                k -= 1
            data[i][k + 1] = key
    return data
            
#сортировка вставкой 
print(MATRIX, "\n")
insert_sorting(matrix1)
print(matrix1, "\n")

print("Время выполнения : ", time.time() - stime)

[[ 3.  2.  3.  5.  6.  6.  4.  3.  7.  5.]
 [ 3.  8.  1. 10.  2.  2.  4.  3.  9.  9.]
 [10.  8.  7.  8.  9. 10.  6.  7.  2.  5.]
 [ 9.  8.  2.  9.  8.  9.  9.  3.  3.  5.]
 [ 4.  2.  3.  6.  6.  2.  7. 10.  8.  9.]
 [ 8.  7.  6.  3.  8.  9.  9.  6.  1. 10.]
 [10.  9.  4.  9.  6.  5.  4.  1.  6.  6.]
 [ 7.  8.  6.  3.  5.  9.  8.  9.  5. 10.]
 [10.  9.  5.  2. 10.  1.  6.  2.  2.  6.]
 [ 7.  2.  8.  9.  6.  6.  8.  6.  4.  3.]] 

[[ 2.  3.  3.  3.  4.  5.  5.  6.  6.  7.]
 [ 1.  2.  2.  3.  3.  4.  8.  9.  9. 10.]
 [ 2.  5.  6.  7.  7.  8.  8.  9. 10. 10.]
 [ 2.  3.  3.  5.  8.  8.  9.  9.  9.  9.]
 [ 2.  2.  3.  4.  6.  6.  7.  8.  9. 10.]
 [ 1.  3.  6.  6.  7.  8.  8.  9.  9. 10.]
 [ 1.  4.  4.  5.  6.  6.  6.  9.  9. 10.]
 [ 3.  5.  5.  6.  7.  8.  8.  9.  9. 10.]
 [ 1.  2.  2.  2.  5.  6.  6.  9. 10. 10.]
 [ 2.  3.  4.  6.  6.  6.  7.  8.  8.  9.]] 

Время выполнения :  0.004000425338745117


In [204]:
#сортировка обменом

stime = time.time()

def merge(left_list, right_list):  
    sorted_list = []
    left_list_index = right_list_index = 0
    left_list_length, right_list_length = len(left_list), len(right_list)
    for _ in range(left_list_length + right_list_length):
        if left_list_index < left_list_length and right_list_index < right_list_length:
            if left_list[left_list_index] <= right_list[right_list_index]:
                sorted_list.append(left_list[left_list_index])
                left_list_index += 1
            else:
                sorted_list.append(right_list[right_list_index])
                right_list_index += 1
        elif left_list_index == left_list_length:
            sorted_list.append(right_list[right_list_index])
            right_list_index += 1
        elif right_list_index == right_list_length:
            sorted_list.append(left_list[left_list_index])
            left_list_index += 1
    return sorted_list


def merge_sort(nums):  
    if len(nums) <= 1:
        return nums 
    mid = len(nums) // 2
    left_list = merge_sort(nums[:mid])
    right_list = merge_sort(nums[mid:])
    return merge(left_list, right_list)

#сортировка обменом
list0 = copy.deepcopy(MATRIX[:][0])
print(list0, "\n")
list0 = merge_sort(list0)  
print(list0, "\n")


print("Время выполнения : ", time.time() - stime)

[3. 2. 3. 5. 6. 6. 4. 3. 7. 5.] 

[2.0, 3.0, 3.0, 3.0, 4.0, 5.0, 5.0, 6.0, 6.0, 7.0] 

Время выполнения :  0.002001523971557617


In [205]:
#сортировка Шелла

stime = time.time()

def shell(seq):
    inc = len(seq) // 2
    while inc:
        for i, el in enumerate(seq):
            while i >= inc and seq[i - inc] > el:
                seq[i] = seq[i - inc]
                i -= inc
            seq[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
        
#сортировка Шелла
data = copy.deepcopy(MATRIX[:][0])
print (data, "\n")
shell(data)
print (data, "\n")

print("Время выполнения : ", time.time() - stime)

[3. 2. 3. 5. 6. 6. 4. 3. 7. 5.] 

[2. 3. 3. 3. 4. 5. 5. 6. 6. 7.] 

Время выполнения :  0.0009982585906982422


In [206]:
#Быстрая сортировка    

stime = time.time()

def partition(nums, low, high):  
    pivot = nums[(low + high) // 2]
    i = low - 1
    j = high + 1
    while True:
        i += 1
        while nums[i] < pivot:
            i += 1

        j -= 1
        while nums[j] > pivot:
            j -= 1

        if i >= j:
            return j

        nums[i], nums[j] = nums[j], nums[i]

def quick_sort(nums):  
    def _quick_sort(items, low, high):
        if low < high:
            split_index = partition(items, low, high)
            _quick_sort(items, low, split_index)
            _quick_sort(items, split_index + 1, high)

    _quick_sort(nums, 0, len(nums) - 1)
        
#Быстрая сортировка    
quick = copy.deepcopy(MATRIX[:][0])
print(quick, "\n")
quick_sort(quick)
print(quick, "\n")

print("Время выполнения : ", time.time() - stime)

[3. 2. 3. 5. 6. 6. 4. 3. 7. 5.] 

[2. 3. 3. 3. 4. 5. 5. 6. 6. 7.] 

Время выполнения :  0.002002239227294922


In [207]:
#Пирамидальная сортировка

stime = time.time()

def heapify(nums, heap_size, root_index):  
    largest = root_index
    left_child = (2 * root_index) + 1
    right_child = (2 * root_index) + 2

    if left_child < heap_size and nums[left_child] > nums[largest]:
        largest = left_child

    if right_child < heap_size and nums[right_child] > nums[largest]:
        largest = right_child

    if largest != root_index:
        nums[root_index], nums[largest] = nums[largest], nums[root_index]
        heapify(nums, heap_size, largest)

def heap_sort(nums):  
    n = len(nums)
    for i in range(n, -1, -1):
        heapify(nums, n, i)

    for i in range(n - 1, 0, -1):
        nums[i], nums[0] = nums[0], nums[i]
        heapify(nums, i, 0)
        
#Пирамидальная сортировка
list1 = copy.deepcopy(MATRIX[:][0])
print(list1, "\n")
heap_sort(list1)  
print(list1, "\n")

print("Время выполнения : ", time.time() - stime)

[3. 2. 3. 5. 6. 6. 4. 3. 7. 5.] 

[2. 3. 3. 3. 4. 5. 5. 6. 6. 7.] 

Время выполнения :  0.0020012855529785156


In [208]:
#турнирная сортировка

stime = time.time()

def heapify(arr, n, i):
    largest = i 
    l = 2 * i + 1   
    r = 2 * i + 2   

    if l < n and arr[i] < arr[l]:
        largest = l

    if r < n and arr[largest] < arr[r]:
        largest = r

    if largest != i:
        arr[i],arr[largest] = arr[largest],arr[i] 

        heapify(arr, n, largest)

def heapSort(arr):
    n = len(arr)

    for i in range(n, -1, -1):
        heapify(arr, n, i)

    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]  
        heapify(arr, i, 0)
        
#турнирная сортировка
arr = copy.deepcopy(MATRIX[:][0])
print (arr, "\n")
heapSort(arr)
n = len(arr)
print (arr, "\n")

print("Время выполнения : ", time.time() - stime)

[3. 2. 3. 5. 6. 6. 4. 3. 7. 5.] 

[2. 3. 3. 3. 4. 5. 5. 6. 6. 7.] 

Время выполнения :  0.0030019283294677734
